{% set name = "colmap" %}
{% set version = "3.8" %}
{% set build = 8 %}

{% set processor = "cpu" if cuda_compiler_version == "None" else "gpu" %}  # [not osx]
{% set processor = "cpu" %}  # [osx]

# Prioritize gpu build if cudatoolkit can be installed (through __cuda virtual package)
{% set build = build + 100 if processor == "gpu" else build %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 02288f8f61692fe38049d65608ed832b31246e7792692376afb712fa4cef8775
    patches:
      - fix_build.patch
      - unvendor_vlfeat.patch  # [unix]
      - fix_find_lz4.patch
      - fix-cuda-toolkit.patch
      - 1809.patch  # [cuda_compiler_version == "12.0"]
      - 1840.patch  # [cuda_compiler_version == "12.0"]
      - 1823.patch  # [cuda_compiler_version == "12.0"]
      - 1838.patch  # [cuda_compiler_version == "12.0"]
      - 1841.patch  # [cuda_compiler_version == "12.0"]

build:
  number: {{ build }}
  skip: true  # [osx and cuda_compiler_version != "None"]
  string: {{ processor }}h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('colmap', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}         # [not osx and cuda_compiler_version != "None"]
    - cmake
    - make                           # [unix]
    - pkg-config
    - ninja
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [unix and not arm64]
    - {{ cdt('mesa-dri-drivers') }}  # [unix and not arm64]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
    - sysroot_linux-64 2.17          # [linux64]
  host:
    # x11 stuff
    - xorg-libxext                   # [unix]
    - xorg-libxdmcp                  # [unix]
    - xorg-libxau                    # [unix]
    - libxcb                         # [unix]
    - xorg-libxfixes                 # [unix]
    - xorg-libxrender                # [unix]
    - xorg-libx11                    # [unix]
    - xorg-libice                    # [unix]
    - xorg-libsm                     # [unix]
    - libglu                         # [linux]
    # deps
    - libblas
    - libcblas
    - libboost-devel
    - suitesparse
    - eigen
    - freeimage
    - glog
    - gflags
    - glew
    - cgal-cpp
    - ceres-solver
    - qt-main
    - git
    - flann
    - sqlite
    - vlfeat                         # [unix]
    - gmp                            # [unix]
    - lz4-c
    - metis
    - libcurand-dev                  # [cuda_compiler_version == "12.0"]
  run:
    - vlfeat                         # [unix]
    - flann
    - xorg-libxext                   # [unix]
    - xorg-libxdmcp                  # [unix]
    - xorg-libxau                    # [unix]
    - libxcb                         # [unix]
    - xorg-libxfixes                 # [unix]
    - xorg-libxrender                # [unix]
    - xorg-libx11                    # [unix]
    - xorg-libice                    # [unix]
    - xorg-libsm                     # [unix]
    - libglu                         # [linux]
    - __cuda >={{ cuda_compiler_version }}  # [not osx and cuda_compiler_version != "None"]

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\colmap.exe (exit 0) else (exit 1)  # [win]
    - test -f $PREFIX/bin/colmap  # [unix]
    - test -f $PREFIX/lib/colmap/libcolmap.a  # [unix]
    - test -f $PREFIX/lib/colmap/libcolmap_cuda.a  # [unix and cuda_compiler_version != "None"]
    - test -f $PREFIX/share/colmap/COLMAPConfig.cmake  # [unix]

about:
  home: https://colmap.github.io/
  license: BSD-3-Clause
  license_file:
    - COPYING.txt
    - lib/LSD/LICENSE
    - lib/PBA/LICENSE  # [cuda_compiler_version != "12.0"]
    - lib/PoissonRecon/LICENSE
    - lib/SiftGPU/LICENSE
  summary: COLMAP is a general-purpose Structure-from-Motion (SfM) and Multi-View Stereo (MVS) pipeline with a graphical and command-line interface.

extra:
  recipe-maintainers:
    - Tobias-Fischer
