# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "colmap-feedstock"
version = "3.52.2"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/colmap-feedstock"
authors = ["@conda-forge/colmap"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build colmap-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13.yaml"
description = "Build colmap-feedstock with variant linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13 directly (without setup scripts)"
[tasks."inspect-linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13.yaml"
description = "List contents of colmap-feedstock packages built for variant linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13"
[tasks."build-linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14.yaml"
description = "Build colmap-feedstock with variant linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14 directly (without setup scripts)"
[tasks."inspect-linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14.yaml"
description = "List contents of colmap-feedstock packages built for variant linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14"
[tasks."build-linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13.yaml"
description = "Build colmap-feedstock with variant linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13 directly (without setup scripts)"
[tasks."inspect-linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13.yaml"
description = "List contents of colmap-feedstock packages built for variant linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13"
[tasks."build-linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14.yaml"
description = "Build colmap-feedstock with variant linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14 directly (without setup scripts)"
[tasks."inspect-linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14.yaml"
description = "List contents of colmap-feedstock packages built for variant linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14"
[tasks."build-osx_64_"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_.yaml"
description = "Build colmap-feedstock with variant osx_64_ directly (without setup scripts)"
[tasks."inspect-osx_64_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_.yaml"
description = "List contents of colmap-feedstock packages built for variant osx_64_"
[tasks."build-osx_arm64_"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_.yaml"
description = "Build colmap-feedstock with variant osx_arm64_ directly (without setup scripts)"
[tasks."inspect-osx_arm64_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_.yaml"
description = "List contents of colmap-feedstock packages built for variant osx_arm64_"
[tasks."build-win_64_cuda_compiler_version12.6"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_cuda_compiler_version12.6.yaml"
description = "Build colmap-feedstock with variant win_64_cuda_compiler_version12.6 directly (without setup scripts)"
[tasks."inspect-win_64_cuda_compiler_version12.6"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_cuda_compiler_version12.6.yaml"
description = "List contents of colmap-feedstock packages built for variant win_64_cuda_compiler_version12.6"
[tasks."build-win_64_cuda_compiler_versionNone"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_cuda_compiler_versionNone.yaml"
description = "Build colmap-feedstock with variant win_64_cuda_compiler_versionNone directly (without setup scripts)"
[tasks."inspect-win_64_cuda_compiler_versionNone"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_cuda_compiler_versionNone.yaml"
description = "List contents of colmap-feedstock packages built for variant win_64_cuda_compiler_versionNone"

[feature.smithy.dependencies]
conda-smithy = "*"
shellcheck = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
